### ISSUE TITLE
Storybook doesn't work when run.

### ISSUE THREAD

**Issue by darshansimha** [argoproj/argo-ui#566] opened 2024-07-09 15:21 UTC
Steps: 
1) git clone the repo
2) Navigate to the argo-ui directory
3) run yarn install
4) run yarn start

Node : v18.20.4

![Screenshot 2024-07-09 at 11 20 58 AM](https://github.com/argoproj/argo-ui/assets/4667739/0decd33e-e2ba-4243-afa9-344a4657bb39)

I just cloned the repo and have made no changes to the code. Please help

**Comment by agilgur5** [comment] 2024-07-10 05:53
Duplicate of #469

**Closed by agilgur5** 2024-07-10 05:53 UTC
